name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    name: 'graalvm compile in ubuntu'
    strategy:
      matrix:
        os: [ ubuntu-latest, ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run script file
        run: |
          export SDKMAN_DIR="$HOME/.sdkman" && curl -s "https://get.sdkman.io?rcupdate=false" | bash
          candidate="quarkus"
          version="3.8.6"
          source $HOME/.sdkman/bin/sdkman-init.sh
          sdk install $candidate $version
        shell:
            bash
      - name: Print Java Environment
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          source $HOME/.sdkman/bin/sdkman-init.sh
          java --version
          native-image --version
          quarkus --version
      - name: Package with native flag
        run: |
          source $HOME/.sdkman/bin/sdkman-init.sh
          quarkus build --native -Dquarkus.native.native-image-xmx=6G
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/target/kinesis_stream_tee-1.0.0-SNAPSHOT-runner
          asset_name: kinesis_stream_tee-${{ matrix.os }}
          tag: ${{ github.ref }}
          overwrite: true