name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    name: 'graalvm compile for macos, windows and ubuntu'
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
          - os: 'macos-latest'
            platform: 'darwin-arm64'
          - os: 'windows-latest'
            platform: 'win-amd64'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Java Environment
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Package with native flag
        run: mvn -Pnative package
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: kinesis_stream_tee-1.0.0-SNAPSHOT-native-image-source-jar/kinesis_stream_tee-1.0.0-SNAPSHOT-runner*
          asset_name: kinesis_stream_tee-${{ matrix.os }}
          tag: ${{ github.ref }}
          overwrite: true